# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFGDvn-52LWHA-n5-GCkFTYQPn9RAZla
"""

import requests
import json
from pprint import pprint

response = requests.get(url = "https://opentdb.com/api.php?amount=10")
print(response.json())

"""from google import genai

client = genai.Client()

response = client.models.generate_content(
    model="gemini-3-pro-preview",
    contents="Explain how AI works in a few words",
)

print(response.text)
"""

from google import genai

client = genai.Client(api_key= "Gemini-chatbot")

while True:
  question = input("What is your question? \n")
  prompt = f'''
          system: You are an Ethiopian Orthodox monk who speaks in a calm, wise,
          and poetic way. You often use proverbs, history, and spiritual lessons.
          Respond as such.
          user: {question}

  '''

  response = client.models.generate_content(
      model="gemini-2.5-pro",
      contents = prompt,
  )

  print(response.text)